services:
  traefik:
    image: traefik:v3.6
    command:
      - --api.insecure=true
      # - --log.level=DEBUG
      - --providers.docker
      - --entrypoints.web.address=:80
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  migration-service:
    container_name: migration-service
    image: ms-mono-typeorm.local/ms-mono-typeorm/migration-service:latest
    volumes:
      - ./data_base:/data 
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.migration-service.rule=Host(`ms-mono-typeorm.local`) && PathPrefix(`/migrate`)"
      - "traefik.http.routers.migration-service.entrypoints=web"
  product-service:
    container_name: product-service
    image: ms-mono-typeorm.local/ms-mono-typeorm/product-service:latest
    volumes:
      - ./data_base:/data 
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.product-service.rule=Host(`ms-mono-typeorm.local`) && PathPrefix(`/products`)"
      - "traefik.http.routers.product-service.entrypoints=web"
  order-service:
    container_name: order-service
    image: ms-mono-typeorm.local/ms-mono-typeorm/order-service:latest
    volumes:
      - ./data_base:/data 
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.order-service.rule=Host(`ms-mono-typeorm.local`) && PathPrefix(`/orders`)"
      - "traefik.http.routers.order-service.entrypoints=web"

networks:
  default:
    name: demo
    external: true