# for debug build use
# docker compose build --no-cache migration-service --progress=plain
services:
  migration-service:
    build:
      context: .
      dockerfile: services/migration-service/Dockerfile
    ports:
      - "3000:80"
    environment:
      DB_DATABASE : ${DB_DATABASE}
    volumes:
      - ./data:/data 
  product-service:
    build:
      context: .
      dockerfile: services/product-service/Dockerfile
    ports:
      - "3002:80"
    environment:
      DB_DATABASE : ${DB_DATABASE}
    volumes:
      - ./data:/data 

  order-service:
    build:
      context: .
      dockerfile: services/order-service/Dockerfile
    ports:
      - "3003:80"
    environment:
      DB_DATABASE : ${DB_DATABASE}
    volumes:
      - ./data:/data 
