services:
  migration-service:
    image: ms-mono-typeorm/migration-service:1.2
    volumes:
      - ./data:/data 
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.migration-service.rule=Host(`ms-mono-typeorm.local`) && PathPrefix(`/migrate`)"
      - "traefik.http.routers.migration-service.entrypoints=web"
  product-service:
    image: ms-mono-typeorm/product-service:1.2
    volumes:
      - ./data:/data 
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.product-service.rule=Host(`ms-mono-typeorm.local`) && PathPrefix(`/products`)"
      - "traefik.http.routers.product-service.entrypoints=web"
  order-service:
    image: ms-mono-typeorm/order-service:1.2
    volumes:
      - ./data:/data 
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.order-service.rule=Host(`ms-mono-typeorm.local`) && PathPrefix(`/orders`)"
      - "traefik.http.routers.order-service.entrypoints=web"

networks:
  default:
    name: demo
    external: true