## Uncomment the poll configuration section here and in the service `environment:` section if you want to enable polling of a repository.
x-poll-config: &poll-config
 POLL_CONFIG: |
  - url: https://github.com/schooltechx/ms-mono-typeorm.git  # This is the repository to poll
    reference: main  # Optional: specify the branch or tag to poll, defaults to 'main'
#      interval: 180  # Optional: specify the interval in seconds to poll the repository, defaults to 180 seconds (3 minutes)
#      target: ""  # Optional: use to target a specific deployment config file, e.g., "test" -> .doco-cd.test.yaml

services:
  registry:
    image: registry:2
    ports:
      - "5000:5000"
    volumes:
      - ./data_registry:/var/lib/registry
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.registry.rule=Host(`ms-mono-typeorm.local`) && PathPrefix(`/v2/`)"
      - "traefik.http.routers.registry.entrypoints=web"
      - "traefik.http.services.registry.loadbalancer.server.port=5000"

  watchtower:
    container_name: watchtower
    image: nickfedor/watchtower
    environment:
      - WATCHTOWER_CLEANUP=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30 express_starter


networks:
  default:
    name: demo
    external: true