# act --workflows .github/workflows/build-push-services.yaml -j build-push-services \
# --input TAG=1.0 --container-options "--add-host ms-mono-typeorm.local:192.168.2.49"
# act -W .github/workflows/build-push-services.yaml -j build-push-services --input TAG="1.0"
name: Build and Push Services

on:
  workflow_dispatch:
    inputs:
      TAG: {required: true, type: string}
      REPO: {required: false, type: string, default: "schooltechx/ms-mono-typeorm"}
        
jobs:
  build-push-services:
    runs-on: ubuntu-latest
    steps:
      - run: |
          git config --global init.defaultBranch main
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          repository: "schooltechx/ms-mono-typeorm"
          ref: "main"
          token: ${{secrets.GH_TOKEN}}

      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v3
      #   with:
      #     config-inline: |
      #       [registry."ms-mono-typeorm.local"]
      #         http = true

      - name: Build and push migration-service
        uses: ./.github/actions/build-services
        with:
          TAG: ${{inputs.TAG}}
          SERVICE_NAME: "migration-service"

      - name: Build and push product-service
        uses: ./.github/actions/build-services
        with:
          TAG: ${{inputs.TAG}}
          SERVICE_NAME: "product-service"

      - name: Build and push order-service
        uses: ./.github/actions/build-services
        with:
          TAG: ${{inputs.TAG}}
          SERVICE_NAME: "order-service"

          
