# act --workflows .github/workflows/build-a-service.yaml -j build-docker --input NAME=migration-service --input TAG=1.0

name: Build a Service
on:
  workflow_dispatch:
    inputs:
      NAME:
        description: "service name, e.g. migration-service, product-service, order-service"
        type: string
      TAG:
        description: "tag for the image"
        type: string

env:
  SERVICE_FOLDER: services/${{github.event.inputs.NAME}}
  IMAGE_NAME: ms-mono-typeorm.local/demo/ms-mono-typeorm/${{github.event.inputs.NAME}}
  IMAGE_TAG: ${{github.event.inputs.TAG}}

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v6
        with:
          repository: "schooltechx/ms-mono-typeorm"
          ref: "main"
          token: ${{secrets.GH_TOKEN}}
          sparse-checkout: |
            ${{env.SERVICE_FOLDER}}
            packages
            
      - run: |
          ls -la . services
      - run: |
          docker build -t ${{env.IMAGE_NAME}}:${{env.IMAGE_TAG}} -t ${{env.IMAGE_NAME}}:latest -f ${{env.SERVICE_FOLDER}}/Dockerfile .
## push to registry if needed
