# act --workflows .github/workflows/build-services.yaml -j build-docker --input TAG=1.0 -s GH_TOKEN=xxxx

name: Build a Service
on:
  workflow_dispatch:
    inputs:
      TAG:
        description: "tag for the image"
        type: string

env:
  REGISTRY_BASE: ms-mono-typeorm.local/ms-mono-typeorm
  IMAGE_TAG: ${{github.event.inputs.TAG}}

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v6
        with:
          repository: "schooltechx/ms-mono-typeorm"
          ref: "main"
          token: ${{secrets.GH_TOKEN}}
      - run: |
          docker build -t ${{env.REGISTRY_BASE}}/migration-service:${{env.IMAGE_TAG}} -t ${{env.REGISTRY_BASE}}/migration-service:latest -f services/migration-service/Dockerfile .
          docker build -t ${{env.REGISTRY_BASE}}/product-service:${{env.IMAGE_TAG}} -t ${{env.REGISTRY_BASE}}/product-service:latest -f services/product-service/Dockerfile .
          docker build -t ${{env.REGISTRY_BASE}}/order-service:${{env.IMAGE_TAG}} -t ${{env.REGISTRY_BASE}}/order-service:latest -f services/order-service/Dockerfile .

## push to registry if needed
