# act --workflows .github/workflows/build-a-service.yaml -j build-docker --input SERVICE_NAME=migration-service --input TAG=1.0

name: Build a Service
on:
  workflow_dispatch:
    inputs:
      SERVICE_NAME:
        description: "service name, e.g. migration-service, product-service, order-service"
        type: string
      TAG:
        description: "tag for the image, e.g. 1.0"
        type: string
env:
  SERVICE_FOLDER: services/${{inputs.SERVICE_NAME}}
  IMAGE_NAME: ms-mono-typeorm.local/demo/${{inputs.SERVICE_NAME}}

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v6
        with:
          repository: "schooltechx/ms-mono-typeorm"
          ref: "main"
          token: ${{secrets.GH_TOKEN}}
          sparse-checkout: |
            ${{env.SERVICE_FOLDER}}
            packages
            
      - run: |
          ls -la . services
      # - run: |
      #     docker build -t ${{env.IMAGE_NAME}}:${{env.IMAGE_TAG}} -t ${{env.IMAGE_NAME}}:latest -f ${{env.SERVICE_FOLDER}}/Dockerfile .

      - name: how to run raw command with buildx and add-host
        run: |
          docker buildx build --platform linux/amd64 \
            --add-host ms-mono-typeorm.local:192.168.2.49 \
            -t ${{env.IMAGE_NAME}}:${{inputs.TAG}} -t ${{env.IMAGE_NAME}}:latest \
            --push -f ${{env.SERVICE_FOLDER}}/Dockerfile .